{
  "hash": "98647388de89176de553d921c96acee3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Wasting Water for Wardrobes: Analyzing Water Stress and Textile Manufacturing in Fast Fashion\"\nauthors:\n  - name: Kelbi Hall\n    affiliation: Colorado State University \n    roles: writing\n    corresponding: true\n  - name: Chloe Rogozinski\n    affiliation: Colorado State University\n    roles: writing\n    corresponding: false\n\nbibliography: references.bib\nformat:\n  html:\n    theme: Lux\n    toc: true\n    toc-depth: 3\n    toc-location: left\n    number-sections: true\n    code-fold: true\n    title-block-banner: true\n    title-block-style: default \n    code-tools: true\n    image: images/banner.jpg\neditor: \n  markdown: \n    wrap: 72\n---\n\n\n\n# Introduction\n\nThe fast fashion industry is among the most polluting in the world,\ncontributing approximately 8% of total global carbon emissions and\nconsuming 20% of all global wastewater about 79 trillion liters (Bailey\net al., 2022). As demand grows, many companies outsource production to\nlow- and middle-income countries due to cheaper labor and manufacturing\ncosts, which in turn drives down prices and boosts consumer appeal.\nAccording to The Environmental Impacts of Fast Fashion on Water Quality,\nbrands today release twice as many collections as they did before the\n2000s. With lower quality and cost, garments are consumed and discarded\nmore rapidly, accelerating water usage and waste (Bailey et al., 2022).\nChemical use in textile production also poses significant environmental\nthreats. Pesticides used in cotton farming lead to runoff that\nintroduces excessive nutrients into waterways, resulting in dead zones\ncaused by algal blooms. Additionally, fabric dyeing processes account\nfor 17–20% of industrial water pollution globally due to the release of\nhazardous chemicals (Bildirici et al., 2024). According to the World\nTrade Organization’s 2022 analysis, China is the largest global textile\nexporter, accounting for 31.7% of exports. Bangladesh and India follow\nwith 7.9% and 3.1% respectively (Bildirici et al., 2024). This project\nfocuses on water-stressed areas in these three major textile-producing\ncountries. China, with 20% of the world’s population, has access to only\n6% of global freshwater. Uneven distribution and widespread pollution\nhave caused severe water scarcity in many regions (Leung, 2023). India\nholds 18% of the world’s population but only 4% of freshwater resources.\nPoor water sanitation practices leave 600 million people without\nreliable access to usable water (World Bank, 2023). Although Bangladesh\nhas access to 3% of the world’s freshwater and accounts for just 2% of\nthe global population, only 40% of its population has access to safe\nwater. Cotton production places immense stress on freshwater\navailability, as growing just one pair of jeans requires 7,500–10,000\nliters of water—the equivalent of what one person would drink over seven\nyears (Bildirici et al., 2024).\n\nOur main focus in this project is to bring into light the realities of\nneglectful consumption of water from the fast fashion industry in\nalready resource scarce countries. \n\n[@w14071073] [@su17010069] [@leung2023china] [@worldbank2022india]\n[@worldbank2023freshwater] [@worldbank2023textiles]\n\n\n# Data/ Materials \n\nThis project used two datasets from the World Bank Open Data portal.\n\nThe first, “Freshwater withdrawals as a proportion of available freshwater resources” [@worldbank2023freshwater]\nreports national water stress levels as the percentage of renewable freshwater resources withdrawn each year. \n\nThe second dataset, “Textile manufacturing, value added (% of manufacturing)”[@worldbank2023textiles], measures the proportion of total manufacturing value attributed to the textile industry by country and year.\n\nBoth datasets were downloaded as Excel files and imported into R. The data were reshaped from wide to long format using the pivot_longer() function and then merged by Country Name, Country Code, and Year. We removed rows with missing values as needed and converted the Year column to numeric. No values were filled in or estimated during this process. For some visualizations, we filtered out countries with water stress values above 300 percent to minimize the influence of extreme outliers.\n\n# Hypothesis\nCountries with higher levels of textile manufacturing output will experience greater water stress due to the industry's high water consumption and pollution, particularly in regions where freshwater resources are already limited.\n\n# Methods\n\nTo examine the relationship between textile manufacturing and water stress, we used a mix of visual analyses and statistical tests that allowed us to explore patterns across countries and over time. We started with scatterplots to visually assess whether countries with higher textile output also experienced higher water stress, focusing on the year 2018 for a clearer snapshot. Filtering out extreme water stress values helped ensure that most countries were visible and not overshadowed by outliers. We highlighted key countries, including top combined offenders and major textile producers, to compare expected and actual results.\nTo understand how these trends changed over time, we used time series visualizations for India, China, and Bangladesh. This helped us explore whether shifts in textile output aligned with changes in water stress. Pearson correlation tests were then applied to measure the strength of the relationship between textile manufacturing and water stress in these countries, offering a statistical complement to the visual trends. A global correlation test across all countries and years was also conducted to see if any broader relationship existed. Lastly, we summarized average textile output and water stress levels to identify the top five countries in each category, which provided context for our findings and helped compare global patterns. Together, these methods allowed us to explore the data from multiple angles and strengthen our analysis.\n\n# Results\n\nThe results showed that there is not a strong or consistent relationship between textile manufacturing and water stress at the national level. In 2018, countries like Egypt, Uzbekistan, and Sri Lanka had the highest combined levels of textile output and water stress, while major fast fashion producers like India, China, and Bangladesh did not. Time series analysis revealed that in India and China, water stress increased over time even as textile manufacturing declined, suggesting other factors such as agriculture, population growth, or climate conditions are driving water scarcity. Bangladesh had high textile manufacturing and low water stress, but incomplete data for many years limits what we can conclude. Overall, correlation tests confirmed these trends, with strong negative correlations in India and China and a very weak global correlation. The top countries for textile production and those with the highest water stress were mostly different, reinforcing that water stress is likely shaped by broader environmental and economic conditions rather than textile manufacturing alone.\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   3.5.2     ✔ tibble    3.2.1\n✔ lubridate 1.9.4     ✔ tidyr     1.3.1\n✔ purrr     1.0.4     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlibrary(readxl)\nlibrary(dplyr)\n\nwater <- read_excel(\"data/API_ER.H2O.FWST.ZS_DS2_en_excel_v2_14076.xls\", skip = 3)\ntextiles <- read_excel(\"data/API_NV.MNF.TXTL.ZS.UN_DS2_en_excel_v2_26490.xls\", skip = 3)\n\nwater_long <- water %>%\n  pivot_longer(cols = matches(\"^\\\\d{4}$\"), names_to = \"Year\", values_to = \"WaterStress\") %>%\n  select(`Country Name`, `Country Code`, Year, WaterStress)\n\ntextiles_long <- textiles %>%\n  pivot_longer(cols = matches(\"^\\\\d{4}$\"), names_to = \"Year\", values_to = \"TextileValue\") %>%\n  select(`Country Name`, `Country Code`, Year, TextileValue)\n\ncombined <- left_join(water_long, textiles_long, by = c(\"Country Name\", \"Country Code\", \"Year\")) %>%\n  mutate(Year = as.numeric(Year))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Preview the textile manufacturing data\ntextiles_long %>%\n  filter(!is.na(TextileValue)) %>%\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   `Country Name` `Country Code` Year  TextileValue\n   <chr>          <chr>          <chr>        <dbl>\n 1 Albania        ALB            2010          26.4\n 2 Albania        ALB            2011          31.5\n 3 Albania        ALB            2012          27.3\n 4 Albania        ALB            2013          31.1\n 5 Albania        ALB            2014          32.7\n 6 Albania        ALB            2015          32.4\n 7 Albania        ALB            2016          33.7\n 8 Albania        ALB            2017          34.9\n 9 Albania        ALB            2018          36.6\n10 Albania        ALB            2019          36.4\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Count missing values\ncat(\"Missing Water Stress values:\", sum(is.na(water_long$WaterStress)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMissing Water Stress values: 11000 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ncat(\"Missing Textile Manufacturing values:\", sum(is.na(textiles_long$TextileValue)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMissing Textile Manufacturing values: 13692 \n```\n\n\n:::\n:::\n\n\n\n## 2018 Scatter plot\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Filter 2018 data\nscatter_data_2018_filtered <- combined %>%\n  filter(Year == 2018, !is.na(WaterStress), !is.na(TextileValue), WaterStress < 300)\n\n# Top 3 countries by composite score (TextileValue * WaterStress)\ntop_countries_2018 <- scatter_data_2018_filtered %>%\n  mutate(score = TextileValue * WaterStress) %>%\n  arrange(desc(score)) %>%\n  slice(1:3)\n\n# Scatterplot\nggplot(scatter_data_2018_filtered, aes(x = TextileValue, y = WaterStress)) +\n  geom_point(alpha = 0.6) +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"blue\") +\n  geom_text(data = top_countries_2018, aes(label = `Country Name`), vjust = -1, hjust = 1.1, size = 3, color = \"red\") +\n  geom_text(data = filter(scatter_data_2018_filtered, `Country Name` %in% c(\"China\", \"India\", \"Bangladesh\")),\n            aes(label = `Country Name`), vjust = 1.5, hjust = -0.1, size = 3) +\n  labs(title = \"Water Stress vs Textile Manufacturing (2018, Filtered)\",\n       x = \"Textile Manufacturing (% of total manufacturing)\",\n       y = \"Water Stress (% of renewable resources)\") +\n  theme_minimal()\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n**Figure 1.** Scatter plot showing the relationship between water stress levels and textile export values by country.\n\n\n## Time Series Plot\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\ntime_series_data <- combined %>%\n  filter(`Country Name` %in% c(\"India\", \"China\", \"Bangladesh\"), !is.na(WaterStress), !is.na(TextileValue))\n\nggplot(time_series_data, aes(x = Year)) +\n  geom_line(aes(y = WaterStress, color = \"Water Stress\"), linetype = \"solid\") +\n  geom_line(aes(y = TextileValue, color = \"Textile Manufacturing\"), linetype = \"dashed\") +\n  facet_wrap(~ `Country Name`) +\n  labs(title = \"Water Stress and Textile Manufacturing Over Time by Country\",\n       y = \"Percentage\",\n       x = \"Year\",\n       color = \"Indicator\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n**Figure 2.** Time series of annual textile export values for China, India, and Bangladesh.\n\n## Correlation Tests\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# India correlation\nindia_data <- combined %>% filter(`Country Name` == \"India\", !is.na(WaterStress), !is.na(TextileValue))\ncor.test(india_data$TextileValue, india_data$WaterStress)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  india_data$TextileValue and india_data$WaterStress\nt = -15.753, df = 18, p-value = 5.662e-12\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.9865618 -0.9133402\nsample estimates:\n       cor \n-0.9655946 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# China correlation\nchina_data <- combined %>% filter(`Country Name` == \"China\", !is.na(WaterStress), !is.na(TextileValue))\ncor.test(china_data$TextileValue, china_data$WaterStress)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  china_data$TextileValue and china_data$WaterStress\nt = -11.808, df = 13, p-value = 2.535e-08\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.9857302 -0.8707596\nsample estimates:\n       cor \n-0.9564088 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Bangladesh correlation\nbangladesh_data <- combined %>% filter(`Country Name` == \"Bangladesh\", !is.na(WaterStress), !is.na(TextileValue))\n```\n:::\n\n\n\n## Top 5 Countries by Average Textile Output and Water Stress\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\ncountry_averages <- combined %>%\n  group_by(`Country Name`) %>%\n  summarize(avg_textile = mean(TextileValue, na.rm = TRUE),\n            avg_water_stress = mean(WaterStress, na.rm = TRUE)) %>%\n  ungroup()\n\ntop_textile <- country_averages %>% arrange(desc(avg_textile)) %>% slice(1:5)\n\ntop_water_stress <- country_averages %>% arrange(desc(avg_water_stress)) %>% slice(1:5)\n\ntop_textile\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 3\n  `Country Name`       avg_textile avg_water_stress\n  <chr>                      <dbl>            <dbl>\n1 Macao SAR, China            55.5           NaN   \n2 Bangladesh                  42.3             5.72\n3 Syrian Arab Republic        37.4           105.  \n4 Cambodia                    37.2             1.04\n5 Pakistan                    32.9           105.  \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ntop_water_stress\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 3\n  `Country Name`       avg_textile avg_water_stress\n  <chr>                      <dbl>            <dbl>\n1 Kuwait                      4.55            2612.\n2 United Arab Emirates        3.42            1373.\n3 Saudi Arabia                3.28             866.\n4 Libya                       6.38             603.\n5 Qatar                       1.52             358.\n```\n\n\n:::\n:::\n\n\n\n## Global Correlation Test\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nglobal_corr_data <- combined %>% filter(!is.na(WaterStress), !is.na(TextileValue))\ncor.test(global_corr_data$TextileValue, global_corr_data$WaterStress)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  global_corr_data$TextileValue and global_corr_data$WaterStress\nt = -3.5162, df = 1853, p-value = 0.0004483\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.12645593 -0.03603367\nsample estimates:\n        cor \n-0.08141232 \n```\n\n\n:::\n:::\n\n\n\n# Discussion\n\nThis study aimed to examine the relationship between textile\nmanufacturing and water stress across countries, focusing particularly\non India, China, and Bangladesh—nations commonly associated with fast\nfashion production. The hypothesis was that higher textile output would\ncorrelate with higher water stress at the national level due to the\nwater-intensive nature of cotton farming, textile dyeing, and fabric\nproduction. However, the results of this analysis reveal a much more\ncomplex relationship, with textile output alone not consistently\nexplaining national water stress patterns.\n\nThe scatterplot analysis for 2018, after filtering extreme water stress\noutliers (above 300%), highlighted that Egypt, Uzbekistan, and Sri Lanka\nhad the highest combined textile output and water stress, while China,\nIndia, and Bangladesh—although top textile producers—did not exhibit the\nhighest water stress levels. This finding challenges the assumption that\nfast fashion-heavy nations automatically face higher water pressures.\n\nThis outcome underscores that water stress is influenced by multiple\nfactors beyond textile manufacturing. For instance,\nagriculture—particularly water-intensive crops—often consumes far more\nwater than industry. Climate variability, population growth,\nurbanization, and government water policies all contribute to water\ndemand and scarcity. The case of Bangladesh illustrates this well.\nDespite being a global leader in textile exports, Bangladesh maintains\nrelatively low water stress (5.7% average), while other textile\nproducers like Syria and Pakistan experience high water stress (above\n100%), withdrawing freshwater at or beyond renewable levels.\n\nThe time series analysis for India, China, and Bangladesh provided\nadditional insight. India’s water stress has steadily increased over\ntime, despite a decline in textile manufacturing output. This suggests\nthat agriculture, particularly rice and sugarcane production, along with\nurban water demands and climate-related shortages, are likely driving\nwater stress in India. China’s water stress remained relatively stable,\neven as textile output decreased gradually. Bangladesh showed limited\ndata, but available trends suggested low water stress relative to its\ntextile manufacturing levels.\n\nThese trends were further reinforced by correlation analyses. India and\nChina both exhibited strong negative correlations between textile\nmanufacturing and water stress (India: r = -0.97, China: r = -0.96, both\np \\< 0.001). This means that as textile output declined, water stress\nincreased in both countries. While counterintuitive, these results align\nwith the time series findings, suggesting that other sectors or broader\nenvironmental changes—such as urbanization or climate factors—are\ndriving national water pressures more than textile output.\n\nFor Bangladesh, the correlation test could not be performed due to\nlimited overlapping data between the two variables. This reflects one of\nthe challenges in working with global datasets—inconsistent data\navailability across countries and years. Even though Bangladesh is a\nmajor textile producer, its water stress patterns could not be fully\nassessed due to gaps in reporting.\n\nDespite the limitations in water stress data for Bangladesh, external literature highlights the environmental impact of its textile sector. For example, a 2024 study titled Water Pollution and the Textile Industry in Bangladesh: Flawed Corporate Practices or Restrictive Opportunities? [@article] details how untreated wastewater from dyeing facilities has severely degraded water quality in Dhaka’s rivers. The study argues that while global brands pressure factories to reduce pollution, local infrastructure and regulatory gaps often leave producers with limited means to adopt cleaner practices. This reinforces the idea that low national water stress levels can mask serious regional water quality issues, especially in industrial clusters\n\nExpanding the scope to a global analysis, a correlation test across all\ncountries and years produced a very weak negative correlation (r =\n-0.08, p \\< 0.001) between textile manufacturing and water stress. While\nstatistically significant because of the large sample size, the\nrelationship is practically negligible, suggesting that globally,\ntextile output is not a reliable predictor of water stress. This\nsupports the idea that local factors, such as climate, agricultural\npractices, and water policies, heavily influence national water\nconditions.\n\nTo further explore this relationship, the study examined the top five\ncountries by average textile manufacturing output and average water\nstress. Among the top textile producers were Macao SAR (China),\nBangladesh, Syria, Cambodia, and Pakistan. These countries had varying\nlevels of water stress, with Bangladesh maintaining low water stress and\nSyria and Pakistan experiencing high water stress (above 100%).\n\nConversely, the top five water-stressed countries—Kuwait, United Arab\nEmirates, Saudi Arabia, Libya, and Qatar—are predominantly arid nations\nwith extremely high water stress levels (ranging from 358% to 2612%).\nHowever, these countries reported low textile manufacturing output\n(below 6.5%). This contrast demonstrates that water scarcity in these\nregions is likely driven by climate conditions and urban/agricultural\ndemands, rather than textile production.\n\nThese findings align with previous research emphasizing the need for\ncontext-specific analyses when addressing water stress. For example,\ncountries like India and China may face water shortages driven by\nagriculture, urban expansion, and climate variability, whereas Middle\nEastern nations contend with naturally scarce water supplies.\n\nThis study challenges the narrative that fast fashion alone is a primary\ncontributor to water stress. While textile manufacturing certainly has a\nsignificant environmental footprint, the data shows that other sectors,\nparticularly agriculture, often exert greater pressure on water\nresources. Water stress is a multifaceted issue, influenced by sectoral\nwater demands, regional climates, technological efficiencies, and policy\ndecisions.\n\nThe analysis also highlighted data limitations, particularly with\nBangladesh, where incomplete records prevented a full correlation\nanalysis. This reflects a broader challenge with global environmental\ndatasets: inconsistent data collection and reporting. Reliable,\ncomprehensive data is crucial for accurate assessments of global\nresource use patterns. Improvements in data standardization and\nreporting are essential for advancing research and informing water\nmanagement strategies.\n\nDespite these limitations, this study offers valuable insights into the\ncomplex relationship between industrial production and water scarcity.\nWhile textile manufacturing is often targeted in sustainability\nconversations, this research suggests the need for multi-sectoral\napproaches to water management, taking into account agriculture, urban\ngrowth, industrial practices, and climate adaptation.\n\nFuture research could expand on these findings by incorporating regional\nor watershed-level data to assess localized water stress. Additionally,\nintegrating water quality data—particularly related to pollution from\ntextile dyeing processes—could provide a more comprehensive picture of\nthe fast fashion industry’s water impacts. Supply chain analyses could\nalso help trace water usage and pollution footprints across different\nstages of textile production, offering a more granular understanding of\nthe industry’s true water footprint.\n\nIn summary, this study contributes to a growing body of research\nemphasizing that global environmental issues cannot be reduced to\nsingle-sector explanations. Textile manufacturing is an important part\nof the conversation, but water stress must be understood within a\nbroader socio-environmental context that considers multiple drivers,\nincluding agriculture, climate, and population dynamics.\n\n# Conclusion\n\nThis study explored whether countries with higher textile manufacturing output experience greater water stress, focusing on major fast fashion producers like India, China, and Bangladesh. While textile production is known for high water use and pollution, the analysis showed that it is not a consistent driver of national water stress based on current global indicators.\n\nIn India and China, water stress has increased even as textile output declined, pointing to other sectors such as agriculture and urban growth as stronger contributors to water pressure. Bangladesh, a leading textile exporter, showed low reported water stress and lacked enough data for full analysis. This raises concerns about data transparency and limited environmental oversight. Research has documented severe pollution from textile wastewater in Bangladesh, suggesting that water quality degradation is widespread but not reflected in national water stress reports.\n\nThese findings show that national-level water stress indicators are too limited to capture the full impact of the textile industry. Pollution and local water degradation often go unmeasured, and countries with weak regulation or strong economic ties to fast fashion may avoid disclosing the full scope of their impact. Without standardized and required reporting on water use and water quality, true accountability remains out of reach.\n\nTo address water stress effectively, we need a broader approach. This includes stronger data collection, better integration of water quality measures, and policies that hold industries responsible for both resource use and pollution. While textile manufacturing plays a major role in water-related issues, it must be viewed as part of a larger system that includes agriculture, cities, and climate.\n\nIn the end, the fast fashion industry's water impact is often hidden in the data, but its consequences are visible in polluted rivers and depleted communities. Real progress will require transparency, regulation, and global accountability that matches the scale of the problem.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}