<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Wasting Water for Wardrobes: Analyzing Water Stress and Textile Manufacturing in Fast Fashion</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-81e35ebdb4125010edbabe6010586085.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script async="" src="https://hypothes.is/embed.js"></script>
<script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script>


<meta name="citation_title" content="Wasting Water for Wardrobes: Analyzing Water Stress and Textile Manufacturing in Fast Fashion">
<meta name="citation_author" content="Kelbi Hall">
<meta name="citation_author" content="Chloe Rogozinski">
<meta name="citation_language" content="en">
<meta name="citation_reference" content="citation_title=The environmental impacts of fast fashion on water quality: A systematic review;,citation_author=K. Bailey;,citation_author=A. Basu;,citation_author=S. Sharma;,citation_publication_date=2022;,citation_cover_date=2022;,citation_year=2022;,citation_issue=7;,citation_doi=10.3390/w14071073;,citation_volume=14;,citation_journal_title=Water (Basel);">
<meta name="citation_reference" content="citation_title=Unraveling the environmental impacts of the fashion industry: A fourier-based analysis of pollution dynamics and causality across five countries;,citation_author=M. Bildirici;,citation_author=I. Türkkahraman;,citation_author=Ö. Ö. Ersin;,citation_publication_date=2025;,citation_cover_date=2025;,citation_year=2025;,citation_issue=1;,citation_doi=10.3390/su17010069;,citation_volume=17;,citation_journal_title=Sustainability;">
<meta name="citation_reference" content="citation_title=Tackling china’s water shortage crisis;,citation_author=K. C. Leung;,citation_publication_date=2023;,citation_cover_date=2023;,citation_year=2023;,citation_fulltext_html_url=https://earth.org/tackling-chinas-water-shortage-crisis/;">
<meta name="citation_reference" content="citation_title=How is india addressing its water needs?;,citation_author=World Bank;,citation_publication_date=2022;,citation_cover_date=2022;,citation_year=2022;,citation_fulltext_html_url=https://www.worldbank.org/en/country/india/brief/world-water-day-2022-how-india-is-addressing-its-water-needs;">
<meta name="citation_reference" content="citation_title=Freshwater withdrawal as % of internal resources (ER.H2O.FWST.ZS);,citation_author=World Bank;,citation_publication_date=2023;,citation_cover_date=2023;,citation_year=2023;,citation_fulltext_html_url=https://data.worldbank.org/indicator/ER.H2O.FWST.ZS;">
<meta name="citation_reference" content="citation_title=Textiles and clothing, value added (% of manufacturing) (NV.MNF.TXTL.ZS.UN);,citation_author=World Bank;,citation_publication_date=2023;,citation_cover_date=2023;,citation_year=2023;,citation_fulltext_html_url=https://data.worldbank.org/indicator/NV.MNF.TXTL.ZS.UN;">
</head>

<body>

<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Wasting Water for Wardrobes: Analyzing Water Stress and Textile Manufacturing in Fast Fashion</h1>
          </div>

    
    <div class="quarto-title-meta-container">
      <div class="quarto-title-meta-column-start">
            <div class="quarto-title-meta-author">
          <div class="quarto-title-meta-heading">Authors</div>
          <div class="quarto-title-meta-heading">Affiliation</div>
          
                <div class="quarto-title-meta-contents">
            <p class="author">Kelbi Hall </p>
          </div>
                <div class="quarto-title-meta-contents">
                    <p class="affiliation">
                        Colorado State University
                      </p>
                  </div>
                      <div class="quarto-title-meta-contents">
            <p class="author">Chloe Rogozinski </p>
          </div>
                <div class="quarto-title-meta-contents">
                    <p class="affiliation">
                        Colorado State University
                      </p>
                  </div>
                    </div>
        
        <div class="quarto-title-meta">

                      
          
                
              </div>
      </div>
      <div class="quarto-title-meta-column-end quarto-other-formats-target">
      <div class="quarto-alternate-formats"><div class="quarto-title-meta-heading">Other Formats</div><div class="quarto-title-meta-contents"><p><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></p></div><div class="quarto-title-meta-contents"><p><a href="index-meca.zip" data-meca-link="true"><i class="bi bi-archive"></i>MECA Bundle</a></p></div></div></div>
    </div>



    <div class="quarto-other-links-text-target">
    </div>  </div>
</header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#data-materials" id="toc-data-materials" class="nav-link" data-scroll-target="#data-materials">Data/ Materials</a></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods">Methods</a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul>
<div class="quarto-alternate-notebooks"><h2>Notebooks</h2><ul><li><a href="index-preview.html"><i class="bi bi-journal-code"></i>Article Notebook</a></li></ul></div></nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content">



  


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>The fast fashion industry is among the most polluting in the world, contributing approximately 8% of total global carbon emissions and consuming 20% of all global wastewater—about 79 trillion liters (Bailey et al., 2022). As demand grows, many companies outsource production to low- and middle-income countries due to cheaper labor and manufacturing costs, which in turn drives down prices and boosts consumer appeal. According to The Environmental Impacts of Fast Fashion on Water Quality, brands today release twice as many collections as they did before the 2000s. With lower quality and cost, garments are consumed and discarded more rapidly, accelerating water usage and waste (Bailey et al., 2022). Chemical use in textile production also poses significant environmental threats. Pesticides used in cotton farming lead to runoff that introduces excessive nutrients into waterways, resulting in dead zones caused by algal blooms. Additionally, fabric dyeing processes account for 17–20% of industrial water pollution globally due to the release of hazardous chemicals (Bildirici et al., 2024). According to the World Trade Organization’s 2022 analysis, China is the largest global textile exporter, accounting for 31.7% of exports. Bangladesh and India follow with 7.9% and 3.1% respectively (Bildirici et al., 2024). This project focuses on water-stressed areas in these three major textile-producing countries. China, with 20% of the world’s population, has access to only 6% of global freshwater. Uneven distribution and widespread pollution have caused severe water scarcity in many regions (Leung, 2023). India holds 18% of the world’s population but only 4% of freshwater resources. Poor water sanitation practices leave 600 million people without reliable access to usable water (World Bank, 2023). Although Bangladesh has access to 3% of the world’s freshwater and accounts for just 2% of the global population, only 40% of its population has access to safe water. Cotton production places immense stress on freshwater availability, as growing just one pair of jeans requires 7,500–10,000 liters of water—the equivalent of what one person would drink over seven years (Bildirici et al., 2024).</p>
<p>Our main focus in this project is to bring into light the realities of neglectful consumption of water from the fast fashion industry in already resource scarce countries.</p>
<p><span class="citation" data-cites="w14071073">(<a href="#ref-w14071073" role="doc-biblioref">Bailey, Basu, and Sharma 2022</a>)</span> <span class="citation" data-cites="su17010069">(<a href="#ref-su17010069" role="doc-biblioref">Bildirici, Türkkahraman, and Ersin 2025</a>)</span> <span class="citation" data-cites="leung2023china">(<a href="#ref-leung2023china" role="doc-biblioref">Leung 2023</a>)</span> <span class="citation" data-cites="worldbank2022india">(<a href="#ref-worldbank2022india" role="doc-biblioref">World Bank 2022</a>)</span> <span class="citation" data-cites="worldbank2023freshwater">(<a href="#ref-worldbank2023freshwater" role="doc-biblioref">World Bank 2023a</a>)</span> <span class="citation" data-cites="worldbank2023textiles">(<a href="#ref-worldbank2023textiles" role="doc-biblioref">World Bank 2023b</a>)</span></p>
</section>
<section id="data-materials" class="level1">
<h1>Data/ Materials</h1>
<p>This project used two datasets from the World Bank Open Data portal.</p>
<p>The first, “Freshwater withdrawals as a proportion of available freshwater resources” <span class="citation" data-cites="worldbank2023freshwater">(<a href="#ref-worldbank2023freshwater" role="doc-biblioref">World Bank 2023a</a>)</span> reports national water stress levels as the percentage of renewable freshwater resources withdrawn each year.</p>
<p>The second dataset, “Textile manufacturing, value added (% of manufacturing)”<span class="citation" data-cites="worldbank2023textiles">(<a href="#ref-worldbank2023textiles" role="doc-biblioref">World Bank 2023b</a>)</span>, measures the proportion of total manufacturing value attributed to the textile industry by country and year.</p>
<p>Both datasets were downloaded as Excel files and imported into R. The data were reshaped from wide to long format using the pivot_longer() function and then merged by Country Name, Country Code, and Year. We removed rows with missing values as needed and converted the Year column to numeric. No values were filled in or estimated during this process. For some visualizations, we filtered out countries with water stress values above 300 percent to minimize the influence of extreme outliers.</p>
</section>
<section id="methods" class="level1">
<h1>Methods</h1>
<p>To examine the relationship between textile manufacturing and water stress, we used a mix of visual analyses and statistical tests that allowed us to explore patterns across countries and over time. We started with scatterplots to visually assess whether countries with higher textile output also experienced higher water stress, focusing on the year 2018 for a clearer snapshot. Filtering out extreme water stress values helped ensure that most countries were visible and not overshadowed by outliers. We highlighted key countries, including top combined offenders and major textile producers, to compare expected and actual results. To understand how these trends changed over time, we used time series visualizations for India, China, and Bangladesh. This helped us explore whether shifts in textile output aligned with changes in water stress. Pearson correlation tests were then applied to measure the strength of the relationship between textile manufacturing and water stress in these countries, offering a statistical complement to the visual trends. A global correlation test across all countries and years was also conducted to see if any broader relationship existed. Lastly, we summarized average textile output and water stress levels to identify the top five countries in each category, which provided context for our findings and helped compare global patterns. Together, these methods allowed us to explore the data from multiple angles and strengthen our analysis.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 4
   `Country Name` `Country Code` Year  TextileValue
   &lt;chr&gt;          &lt;chr&gt;          &lt;chr&gt;        &lt;dbl&gt;
 1 Albania        ALB            2010          26.4
 2 Albania        ALB            2011          31.5
 3 Albania        ALB            2012          27.3
 4 Albania        ALB            2013          31.1
 5 Albania        ALB            2014          32.7
 6 Albania        ALB            2015          32.4
 7 Albania        ALB            2016          33.7
 8 Albania        ALB            2017          34.9
 9 Albania        ALB            2018          36.6
10 Albania        ALB            2019          36.4</code></pre>
</div>
<a class="quarto-notebook-link" id="nblink-1" href="index-preview.html">Source: Article Notebook</a></div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Missing Water Stress values: 11000 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Missing Textile Manufacturing values: 13692 </code></pre>
</div>
</div>
<p>2018 Scatter plot</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/unnamed-chunk-4-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1"><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
</div>
<p>Time Series Plot</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/unnamed-chunk-5-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2"><img src="index_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
</div>
<p>Correlation Tests</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  india_data$TextileValue and india_data$WaterStress
t = -15.753, df = 18, p-value = 5.662e-12
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.9865618 -0.9133402
sample estimates:
       cor 
-0.9655946 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  china_data$TextileValue and china_data$WaterStress
t = -11.808, df = 13, p-value = 2.535e-08
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.9857302 -0.8707596
sample estimates:
       cor 
-0.9564088 </code></pre>
</div>
</div>
<p>Top 5 Countries by Average Textile Output and Water Stress</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 3
  `Country Name`       avg_textile avg_water_stress
  &lt;chr&gt;                      &lt;dbl&gt;            &lt;dbl&gt;
1 Macao SAR, China            55.5           NaN   
2 Bangladesh                  42.3             5.72
3 Syrian Arab Republic        37.4           105.  
4 Cambodia                    37.2             1.04
5 Pakistan                    32.9           105.  </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 3
  `Country Name`       avg_textile avg_water_stress
  &lt;chr&gt;                      &lt;dbl&gt;            &lt;dbl&gt;
1 Kuwait                      4.55            2612.
2 United Arab Emirates        3.42            1373.
3 Saudi Arabia                3.28             866.
4 Libya                       6.38             603.
5 Qatar                       1.52             358.</code></pre>
</div>
</div>
<p>Global Correlation Test</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  global_corr_data$TextileValue and global_corr_data$WaterStress
t = -3.5162, df = 1853, p-value = 0.0004483
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.12645593 -0.03603367
sample estimates:
        cor 
-0.08141232 </code></pre>
</div>
</div>
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
<p>This study aimed to examine the relationship between textile manufacturing and water stress across countries, focusing particularly on India, China, and Bangladesh—nations commonly associated with fast fashion production. The hypothesis was that higher textile output would correlate with higher water stress at the national level due to the water-intensive nature of cotton farming, textile dyeing, and fabric production. However, the results of this analysis reveal a much more complex relationship, with textile output alone not consistently explaining national water stress patterns.</p>
<p>The scatterplot analysis for 2018, after filtering extreme water stress outliers (above 300%), highlighted that Egypt, Uzbekistan, and Sri Lanka had the highest combined textile output and water stress, while China, India, and Bangladesh—although top textile producers—did not exhibit the highest water stress levels. This finding challenges the assumption that fast fashion-heavy nations automatically face higher water pressures.</p>
<p>This outcome underscores that water stress is influenced by multiple factors beyond textile manufacturing. For instance, agriculture—particularly water-intensive crops—often consumes far more water than industry. Climate variability, population growth, urbanization, and government water policies all contribute to water demand and scarcity. The case of Bangladesh illustrates this well. Despite being a global leader in textile exports, Bangladesh maintains relatively low water stress (5.7% average), while other textile producers like Syria and Pakistan experience high water stress (above 100%), withdrawing freshwater at or beyond renewable levels.</p>
<p>The time series analysis for India, China, and Bangladesh provided additional insight. India’s water stress has steadily increased over time, despite a decline in textile manufacturing output. This suggests that agriculture, particularly rice and sugarcane production, along with urban water demands and climate-related shortages, are likely driving water stress in India. China’s water stress remained relatively stable, even as textile output decreased gradually. Bangladesh showed limited data, but available trends suggested low water stress relative to its textile manufacturing levels.</p>
<p>These trends were further reinforced by correlation analyses. India and China both exhibited strong negative correlations between textile manufacturing and water stress (India: r = -0.97, China: r = -0.96, both p &lt; 0.001). This means that as textile output declined, water stress increased in both countries. While counterintuitive, these results align with the time series findings, suggesting that other sectors or broader environmental changes—such as urbanization or climate factors—are driving national water pressures more than textile output.</p>
<p>For Bangladesh, the correlation test could not be performed due to limited overlapping data between the two variables. This reflects one of the challenges in working with global datasets—inconsistent data availability across countries and years. Even though Bangladesh is a major textile producer, its water stress patterns could not be fully assessed due to gaps in reporting.</p>
<p>Expanding the scope to a global analysis, a correlation test across all countries and years produced a very weak negative correlation (r = -0.08, p &lt; 0.001) between textile manufacturing and water stress. While statistically significant because of the large sample size, the relationship is practically negligible, suggesting that globally, textile output is not a reliable predictor of water stress. This supports the idea that local factors, such as climate, agricultural practices, and water policies, heavily influence national water conditions.</p>
<p>To further explore this relationship, the study examined the top five countries by average textile manufacturing output and average water stress. Among the top textile producers were Macao SAR (China), Bangladesh, Syria, Cambodia, and Pakistan. These countries had varying levels of water stress, with Bangladesh maintaining low water stress and Syria and Pakistan experiencing high water stress (above 100%).</p>
<p>Conversely, the top five water-stressed countries—Kuwait, United Arab Emirates, Saudi Arabia, Libya, and Qatar—are predominantly arid nations with extremely high water stress levels (ranging from 358% to 2612%). However, these countries reported low textile manufacturing output (below 6.5%). This contrast demonstrates that water scarcity in these regions is likely driven by climate conditions and urban/agricultural demands, rather than textile production.</p>
<p>These findings align with previous research emphasizing the need for context-specific analyses when addressing water stress. For example, countries like India and China may face water shortages driven by agriculture, urban expansion, and climate variability, whereas Middle Eastern nations contend with naturally scarce water supplies.</p>
<p>This study challenges the narrative that fast fashion alone is a primary contributor to water stress. While textile manufacturing certainly has a significant environmental footprint, the data shows that other sectors, particularly agriculture, often exert greater pressure on water resources. Water stress is a multifaceted issue, influenced by sectoral water demands, regional climates, technological efficiencies, and policy decisions.</p>
<p>The analysis also highlighted data limitations, particularly with Bangladesh, where incomplete records prevented a full correlation analysis. This reflects a broader challenge with global environmental datasets: inconsistent data collection and reporting. Reliable, comprehensive data is crucial for accurate assessments of global resource use patterns. Improvements in data standardization and reporting are essential for advancing research and informing water management strategies.</p>
<p>Despite these limitations, this study offers valuable insights into the complex relationship between industrial production and water scarcity. While textile manufacturing is often targeted in sustainability conversations, this research suggests the need for multi-sectoral approaches to water management, taking into account agriculture, urban growth, industrial practices, and climate adaptation.</p>
<p>Future research could expand on these findings by incorporating regional or watershed-level data to assess localized water stress. Additionally, integrating water quality data—particularly related to pollution from textile dyeing processes—could provide a more comprehensive picture of the fast fashion industry’s water impacts. Supply chain analyses could also help trace water usage and pollution footprints across different stages of textile production, offering a more granular understanding of the industry’s true water footprint.</p>
<p>In summary, this study contributes to a growing body of research emphasizing that global environmental issues cannot be reduced to single-sector explanations. Textile manufacturing is an important part of the conversation, but water stress must be understood within a broader socio-environmental context that considers multiple drivers, including agriculture, climate, and population dynamics.</p>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>This study set out to explore the relationship between textile manufacturing and water stress across countries, focusing on major fast fashion producers such as India, China, and Bangladesh. While textile production is known for its high water consumption and pollution potential, the analysis revealed that it is not a consistent driver of national water stress. Both the scatterplot and time series analyses, along with correlation tests, showed that water stress levels do not reliably correlate with textile manufacturing output.</p>
<p>In India and China, strong negative correlations indicated that water stress has increased even as textile manufacturing output declined, suggesting that other sectors, particularly agriculture and urban development, play larger roles in shaping national water pressures. At the global level, a very weak negative correlation further emphasized that textile output alone is not a reliable predictor of water stress.</p>
<p>The top textile-producing countries and the top water-stressed nations were largely distinct, reinforcing that regional factors such as climate, resource management, and sectoral water use have greater influence on water scarcity.</p>
<p>These findings highlight the complexity of water resource management and suggest that addressing global water stress requires a multi-sectoral approach, focusing not only on industrial output, but also on agriculture, urbanization, and climate adaptation strategies. While textile production remains a key area for sustainability improvements, including reducing water pollution from dyeing and improving water efficiency, it should be understood as part of a broader system of water use.</p>
<p>Moving forward, improving data completeness and consistency across countries will be critical to fully understanding global water stress patterns. Future research should also explore regional water stress dynamics, supply chain impacts, and water quality to build a more comprehensive view of the fast fashion industry’s environmental footprint.</p>
<p>In conclusion, while fast fashion remains a significant environmental concern, this study emphasizes that water stress is a multi-dimensional challenge requiring holistic solutions. Sustainable water management will depend on integrating sectoral demands, addressing local contexts, and collaborating across industries to ensure that water resources are protected for both current and future generations.</p>

</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-w14071073" class="csl-entry" role="listitem">
Bailey, K., A. Basu, and S. Sharma. 2022. <span>“The Environmental Impacts of Fast Fashion on Water Quality: A Systematic Review.”</span> <em>Water (Basel)</em> 14 (7): 1073. <a href="https://doi.org/10.3390/w14071073">https://doi.org/10.3390/w14071073</a>.
</div>
<div id="ref-su17010069" class="csl-entry" role="listitem">
Bildirici, M., I. Türkkahraman, and Ö. Ö. Ersin. 2025. <span>“Unraveling the Environmental Impacts of the Fashion Industry: A Fourier-Based Analysis of Pollution Dynamics and Causality Across Five Countries.”</span> <em>Sustainability</em> 17 (1): 69. <a href="https://doi.org/10.3390/su17010069">https://doi.org/10.3390/su17010069</a>.
</div>
<div id="ref-leung2023china" class="csl-entry" role="listitem">
Leung, K. C. 2023. <span>“Tackling China’s Water Shortage Crisis.”</span> 2023. <a href="https://earth.org/tackling-chinas-water-shortage-crisis/">https://earth.org/tackling-chinas-water-shortage-crisis/</a>.
</div>
<div id="ref-worldbank2022india" class="csl-entry" role="listitem">
World Bank. 2022. <span>“How Is India Addressing Its Water Needs?”</span> 2022. <a href="https://www.worldbank.org/en/country/india/brief/world-water-day-2022-how-india-is-addressing-its-water-needs">https://www.worldbank.org/en/country/india/brief/world-water-day-2022-how-india-is-addressing-its-water-needs</a>.
</div>
<div id="ref-worldbank2023freshwater" class="csl-entry" role="listitem">
———. 2023a. <span>“Freshwater Withdrawal as % of Internal Resources (ER.H2O.FWST.ZS).”</span> <a href="https://data.worldbank.org/indicator/ER.H2O.FWST.ZS">https://data.worldbank.org/indicator/ER.H2O.FWST.ZS</a>.
</div>
<div id="ref-worldbank2023textiles" class="csl-entry" role="listitem">
———. 2023b. <span>“Textiles and Clothing, Value Added (% of Manufacturing) (NV.MNF.TXTL.ZS.UN).”</span> <a href="https://data.worldbank.org/indicator/NV.MNF.TXTL.ZS.UN">https://data.worldbank.org/indicator/NV.MNF.TXTL.ZS.UN</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>